% Plot Residual 1.2
if(mod(it,nfrec)==0)
% Plot configuration
figure(9)

dlr11 = plot(it,err1,'o','color',color(1,:),'LineWidth',1.2,...
        'MarkerFaceColor',color(1,:),'MarkerEdgeColor','black',...
        'MarkerSize',8);
dlr12 = plot(it,err2,'d','color',color(2,:),'LineWidth',1.2,...
        'MarkerFaceColor',color(2,:),'MarkerEdgeColor','black',...
        'MarkerSize',8);
dlr13 = plot(it,err3,'v','color',color(3,:),'LineWidth',1.2,...
        'MarkerFaceColor',color(3,:),'MarkerEdgeColor','black',...
        'MarkerSize',8);
legend([dlr11,dlr12,dlr13],leg2,'FontSize',20,'Location','northeastoutside','interpreter','latex');

% variable time step
% dlr21= plot(it,err1,'o','color',color(1,:),'LineWidth',1.2,...
%         'MarkerFaceColor','white','MarkerEdgeColor',color(1,:),...
%         'MarkerSize',8);
% dlr22= plot(it,err2,'d','color',color(2,:),'LineWidth',1.2,...
%         'MarkerFaceColor','white','MarkerEdgeColor',color(2,:),...
%         'MarkerSize',8);
% dlr23= plot(it,err3,'v','color',color(3,:),'LineWidth',1.2,...
%         'MarkerFaceColor','white','MarkerEdgeColor',color(3,:),...
%         'MarkerSize',8);
% legend([dlr21,dlr22,dlr23],leg2(4:6),'FontSize',20,'Location','northeastoutside','interpreter','latex');
% legend([dlr11,dlr12,dlr13,dlr21,dlr22,dlr23],leg2,'FontSize',20,'Location','northeastoutside','interpreter','latex');
end