% Plot Mixing, TKE and k-epsilon
% Plot configuration
descr = {strcat('$N_{DNS} = ',num2str(length(y_dns)),'$');
         strcat('$N_{TKE} = ',num2str(length(y_tke)),'$');
         strcat('$N_{k-\epsilon_{C}} = ',num2str(length(y_kepsilon)),'$');
         strcat('$N_{k-\epsilon_{NT}} = ',num2str(length(y_kepsilon2)),'$')};
leg{1}='DNS'; leg{2}='TKE'; leg{3}='$k-\epsilon_{C}$';
leg{4}='$k-\epsilon_{NT}$';
color = colours;
fig = figure;
set(fig,'innerposition',[250 150 1000 600],...
        'outerposition',[250 150 1000 600]);
set(axes,'LineWidth',1.4,'FontSize',20,'BoxStyle','full')    
grid on; box on; hold on; axis tight;
% text(18,4.25,descr,'interpreter','latex','FontSize',26,'Units','centimeters')
xlabel('$y/h$','FontSize',26,'interpreter','latex');
ylabel('$\epsilon/(u_\tau^3/h)$','FontSize',26,'interpreter','latex');
% plot(y_dns,ep_dns,'-o','color',color(1,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(1,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_tke,ep_tke,'-s','color',color(3,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(3,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_kepsilon,ep_kepsilon,'-d','color',color(4,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(4,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_kepsilon2,ep_kepsilon2,'-v','color',color(5,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(5,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)

plot(y_dns,ep_dns,'-','color',color(1,:),'LineWidth',2,...
    'MarkerFaceColor',color(1,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_tke,ep_tke,'-','color',color(3,:),'LineWidth',2,...
    'MarkerFaceColor',color(3,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_kepsilon,ep_kepsilon+D_kepsilon,'-','color',color(4,:),'LineWidth',2,...
    'MarkerFaceColor',color(4,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_kepsilon2,ep_kepsilon2,'-','color',color(5,:),'LineWidth',2,...
    'MarkerFaceColor',color(5,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)

legend(leg,'FontSize',26,'Location','northeastoutside','interpreter','latex');
tit = strcat('$Re_\tau = ',num2str(Re),'$');
title({tit},'Interpreter','latex','FontSize',26);

if savefigure
    filename2 = strcat(fpath,strcat('all_ep',num2str(Re)));
    saveas(fig,filename2,'epsc');
end