% Plot Mixing, TKE and k-epsilon
load(strcat('mixing_',num2str(Re),'.mat'));
load(strcat('tke_',num2str(Re),'.mat'));
load(strcat('kepsilon_',num2str(Re),'.mat'));
load(strcat('kepsilon2_',num2str(Re),'NT.mat'));
% Plot configuration
descr = {strcat('$N_{DNS} = ',num2str(length(y_dns)),'$');
         strcat('$N_{mixing} = ',num2str(length(y_mixing)),'$');
         strcat('$N_{TKE} = ',num2str(length(y_tke)),'$');
         strcat('$N_{k-\epsilon_{C}} = ',num2str(length(y_kepsilon)),'$');
         strcat('$N_{k-\epsilon_{NT}} = ',num2str(length(y_kepsilon2)),'$')};
leg{1}='DNS'; leg{2}='Mixing'; 
leg{3}='TKE'; leg{4}='$k-\epsilon_{C}$';
leg{5}='$k-\epsilon_{NT}$';
color = colours;
fig = figure;
set(fig,'innerposition',[250 150 1000 600],...
        'outerposition',[250 150 1000 600]);
set(axes,'LineWidth',1.4,'FontSize',20,'BoxStyle','full')    
grid on; box on; hold on; axis tight;
% text(17.5,3,descr,'interpreter','latex','FontSize',26,'Units','centimeters')
xlabel('$y/h$','FontSize',26,'interpreter','latex');
ylabel('$\langle u\rangle /u_\tau$','FontSize',26,'interpreter','latex');
ylim([0,25])
% plot(y_dns,u_dns,'-o','color',color(1,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(1,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_mixing,u_mixing,'-<','color',color(2,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(2,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_tke,u_tke,'-s','color',color(3,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(3,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_kepsilon,u_kepsilon,'-d','color',color(4,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(4,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)
% plot(y_kepsilon2,u_kepsilon2,'-v','color',color(5,:),'LineWidth',1.4,...
%     'MarkerFaceColor',color(5,:),'MarkerEdgeColor','black',...
%     'MarkerSize',5)

plot(y_dns,u_dns,'-','color',color(1,:),'LineWidth',2,...
    'MarkerFaceColor',color(1,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_mixing,u_mixing,'-','color',color(2,:),'LineWidth',2,...
    'MarkerFaceColor',color(2,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_tke,u_tke,'-','color',color(3,:),'LineWidth',2,...
    'MarkerFaceColor',color(3,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_kepsilon,u_kepsilon,'-','color',color(4,:),'LineWidth',2,...
    'MarkerFaceColor',color(4,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)
plot(y_kepsilon2,u_kepsilon2,'-','color',color(5,:),'LineWidth',2,...
    'MarkerFaceColor',color(5,:),'MarkerEdgeColor','black',...
    'MarkerSize',5)

legend(leg,'FontSize',26,'Location','northeastoutside','interpreter','latex')
tit = strcat('$Re_\tau = ',num2str(Re),'$');
title({tit},'Interpreter','latex','FontSize',26);

if savefigure
    filename2 = strcat(fpath,strcat('all_u',num2str(Re)));
    saveas(fig,filename2,'epsc');
end